### ISSUE TITLE
Quick Install App

### ISSUE THREAD

**Issue by Ibrram** [cdgco/HestiaWebInterface#17]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
In hestiaCP when you edit the domain you'll find a button "Quick Install App" i hope it be in HestiaWebInterface or even add a WordPress Installer

**Comment by cdgco** [comment]
"Quick Install App Support" is already part of the to-do list (#1). I have no estimated timeframe to when this might be added.
