### ISSUE TITLE
Internal Server Error Oops! Something went wrong. 

### ISSUE THREAD

**Issue by BartManX** [cdgco/HestiaWebInterface#4]
Operating System:Ubuntu 20.04 (x86_64)
Hestia Control Panel:  v1.3.5 

 bash <(curl -s https://cdgco.github.io/hst-full)
Checking for required packages ...
wget found
tar found
git found

Installing Hestia Web Interface frontend ...
Installing Hestia Web Interface backend ...

Installation Complete! Please visit your website online to finish configuration.

when I go to the installed domain I get :

Internal Server Error
Oops! Something went wrong.

The server encountered an internal error or misconfiguration and was unable to complete your request.

Error Code: 500

**Comment by cdgco** [comment]
Could you send your error log (/home/USER/web/DOMAIN/logs/DOMAIN.error.log in HestiaCP) and the version of PHP you're using?

**Comment by BartManX** [comment]
> Could you send your error log (/home/USER/web/DOMAIN/logs/DOMAIN.error.log in HestiaCP) and the output of this command: `bash <(curl -s https://cdgco.github.io/hst-debug)`?

is there  a way to do this without showing my info to anybody that rolls up on this ?

**Comment by cdgco** [comment]
Feel free to strip any identifiable info from the logs if needed, I'd only like to see the most recent errors for a single request, not the whole file. You can also email them to me at carter@cdgtech.one.

**Comment by BartManX** [comment]
[Tue Apr 20 00:39:27.996203 2021] [core:alert] [pid 6164:tid 140589722994432] [client ***.**.**.**:0] /home/admin/web/s1.domain.com/public_html/.htaccess: Invalid command 'php_flag', perhaps misspelled or defined by a module not included in the server configuration
[Tue Apr 20 00:39:28.782103 2021] [core:alert] [pid 6163:tid 140589911836416] [client ***.**.**.**:0] /home/admin/web/s1.domain.com/public_html/.htaccess: Invalid command 'php_flag', perhaps misspelled or defined by a module not included in the server configuration
[Tue Apr 20 00:39:36.780486 2021] [core:alert] [pid 6164:tid 140589714601728] [client ***.**.**.**:0] /home/admin/web/s1.domain.com/public_html/.htaccess: Invalid command 'php_flag', perhaps misspelled or defined by a module not included in the server configuration
[Tue Apr 20 00:39:37.514716 2021] [core:alert] [pid 6164:tid 140589689423616] [client ***.**.**.**:0] /home/admin/web/s1.domain.com/public_html/.htaccess: Invalid command 'php_flag', perhaps misspelled or defined by a module not included in the server configuration
[Tue Apr 20 00:40:04.420686 2021] [core:alert] [pid 6164:tid 140589664245504] [client ***.**.**.**:0] /home/admin/web/s1.domain.com/public_html/.htaccess: Invalid command 'php_flag', perhaps misspelled or defined by a module not included in the server configuration
[Tue Apr 20 00:40:05.267911 2021] [core:alert] [pid 6163:tid 140589886658304] [client ***.**.**.**:0] /home/admin/web/s1.domain.com/public_html/.htaccess: Invalid command 'php_flag', perhaps misspelled or defined by a module not included in the server configuration, referer: https://s1.domain.com/
[Tue Apr 20 00:41:51.244143 2021] [core:alert] [pid 6163:tid 140589869872896] [client ***.**.**.**:0] /home/admin/web/s1.domain.com/public_html/.htaccess: Invalid command 'php_flag', perhaps misspelled or defined by a module not included in the server configuration
[Tue Apr 20 00:41:51.944575 2021] [core:alert] [pid 6164:tid 140589773350656] [client ***.**.**.**:0] /home/admin/web/s1.domain.com/public_html/.htaccess: Invalid command 'php_flag', perhaps misspelled or defined by a module not included in the server configuration
[Tue Apr 20 00:42:00.441175 2021] [core:alert] [pid 6163:tid 140589781743360] [client ***.**.**.**:0] /home/admin/web/s1.domain.com/public_html/.htaccess: Invalid command 'php_flag', perhaps misspelled or defined by a module not included in the server configuration
[Tue Apr 20 00:42:01.143287 2021] [core:alert] [pid 6164:tid 140589748172544] [client ***.**.**.**:0] /home/admin/web/s1.domain.com/public_html/.htaccess: Invalid command 'php_flag', perhaps misspelled or defined by a module not included in the server configuration
[Tue Apr 20 00:44:22.458693 2021] [core:alert] [pid 6163:tid 140589748172544] [client 205.169.39.55:0] /home/admin/web/s1.domain.com/public_html/.htaccess: Invalid command 'php_flag', perhaps misspelled or defined by a module not included in the server configuration
[Tue Apr 20 00:49:01.387839 2021] [core:alert] [pid 6163:tid 140589697816320] [client ***.**.**.**:0] /home/admin/web/s1.domain.com/public_html/.htaccess: Invalid command 'php_flag', perhaps misspelled or defined by a module not included in the server configuration
[Tue Apr 20 00:49:02.105437 2021] [core:alert] [pid 6163:tid 140589639067392] [client ***.**.**.**:0] /home/admin/web/s1.domain.com/public_html/.htaccess: Invalid command 'php_flag', perhaps misspelled or defined by a module not included in the server configuration



root@s1:/home/admin/web/s1.domain.com/public_html# bash <(curl -s https://cdgco.github.io/hst-debug)


No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
VERSION
--------
7.4
max_execution_time   30
max_input_time       60
memory_limit         128M
error_reporting      E_ALL                     &  ~E_DEPRECATED  &  ~E_STRICT
display_errors       Off
post_max_size        8M
upload_max_filesize  2M
config_path          /etc/php/7.4/fpm/php.ini
Web Server:                       apache2:8080 (www-data)
SSL Support:                      mod_ssl:8443
Web Backend:                      php-fpm
Proxy Server:                     nginx:80
Proxy SSL:                        nginx:443
Statistics Engine:                awstats
FTP Server:                       vsftpd
Mail Server:                      exim4 + dovecot + clamav-daemon + spamassassin
Webmail alias:                    webmail
Database:                         mysql
phpMyAdmin Alias:                 phpmyadmin
DNS Server:                       bind9
CRON daemon:                      cron
Firewall:                         iptables+ fail2ban
Backups:                          local
Backup Directory:                 /backup
Disk Quota enabled:               no
Version:                          1.3.5
File Manager enabled:             true
Release Branch:                   release
Theme:                            dark
Updates: Notify by email:
Updates: Email install log:
NAME           STATE    CPU  MEM   UPTIME
----           -----    ---  ---   ------
apache2        running  0    442   57
php-fpm        running  0    7     50
nginx          running  0    6     72
bind9          running  0    45    72
exim4          running  0    4     50
dovecot        running  0    0     50
clamav-daemon  running  0.2  1097  50
spamassassin   running  0    265   50
mariadb        running  0    406   50
vsftpd         running  0    1     50
cron           running  0    0     50
ssh            running  0    5     50
iptables       running  0    0     50
fail2ban       running  0    132   72
root@s1:/home/admin/web/s1.domain.com/public_html#

**Comment by cdgco** [comment]
Although it should be commented out, it looks like PHP-FPM is still throwing errors for this line in the .htaccess file: `# php_flag display_errors On`. Go ahead and delete that line then try again (may need to restart apache2 / php-fpm)

**Comment by BartManX** [comment]
that did the trick .. thanks
